export const LISTING_CATEGORIES = [
  "Art & Inspiration",
  "Auto & Parts",
  "Baby & Kids",
  "Beauty & Jewelry",
  "Books & Movies",
  "Business & Career",
  "Church & Ministry",
  "Clothing & Fashion",
  "Computers & Electronics",
  "Events",
  "Finance & Insurance",
  "Food & Restaurants",
  "Fun & Entertainment",
  "Furniture & Appliances",
  "Garage Sale",
  "Hardware & Construction",
  "Internet & IT",
  "Jobs & Careers",
  "Lawn & Garden",
  "Legal & Consulting",
  "Media & Production",
  "Medical & Healthcare",
  "Miscellaneous",
  "Pets & Animals",
  "Photo & Video",
  "Real Estate",
  "Rehab & Recovery",
  "Safety & Security",
  "Sales & Marketing",
  "Science & Technology",
  "Service & Repair",
  "Sports & Fitness",
  "Toys & Games",
  "Vacation & Travel",
] as const;

export type ListingCategory = (typeof LISTING_CATEGORIES)[number];